name = "app"
compatibility_date = "2026-08-12"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_dHJ1c3R5LWdvYmJsZXItODkuY2xlcmsuYWNjb3VudHMuZGV2JA"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL = "/"
NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL = "/"
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "xz19clpr"
QWEN_BASE_URL = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"

[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "c12018a8922b49ed9004f79c823de6d0"
